import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, BookOpen, History, Search } from 'lucide-react'
import { CONTENT_LABELS, KIND_LABELS, dossier, filterRecords, latestRecords, sourceLink } from '@/lib/knowledge/dossier'
import type { KnowledgeRecord } from '@/lib/knowledge/vault'

export type MemoryQuery = { q?: string; tipo?: string; id?: string; version?: string }
const date = (s: string) => new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium', timeZone: 'Europe/Madrid', ...(s.includes('T') ? { timeStyle: 'short' as const } : {}) }).format(new Date(s))
const href = (base: string, query: MemoryQuery) => `${base}?${new URLSearchParams(Object.entries(query).filter(([, v]) => v) as [string, string][]).toString()}`
const panel = 'rounded-2xl border border-slate-200 bg-white p-5 sm:p-7'
const badge = 'inline-flex rounded-full bg-amber-50 px-3 py-1 text-xs font-medium text-amber-900'

export function MemoryView({ records, query, base = '/admin/memoria', status = 'ready', demo = false }: {
  records: KnowledgeRecord[]; query: MemoryQuery; base?: string; status?: 'ready' | 'unconfigured' | 'unavailable'; demo?: boolean
}) {
  const item = query.id ? dossier(records, query.id, query.version) : null
  const filtered = filterRecords(records, query.q, query.tipo)
  const latest = latestRecords(records)
  const back = href(base, { q: query.q, tipo: query.tipo })
  return <div className="mx-auto max-w-6xl px-4 py-7 text-slate-900 sm:px-8 sm:py-10">
    {demo && <div className="mb-6 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-900"><strong>Demostración con datos ficticios.</strong> Sirve para probar el recorrido; no contiene normas ni noticias reales.</div>}
    <header className="mb-7"><p className="mb-2 text-xs font-semibold uppercase tracking-[.18em] text-sky-700">RegTrack · memoria documental</p>
      <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{item ? item.selected.title : 'Tu archivo, con contexto.'}</h1>
      <p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{item ? 'Una lectura comprensible, el texto que la respalda y su historial.' : 'Consulta lo que has encontrado, conserva lo que cambia y vuelve siempre a la fuente.'}</p>
    </header>
    {status !== 'ready' ? <section className={panel}><h2 className="text-xl font-semibold">{status === 'unconfigured' ? 'La memoria aún no está conectada' : 'No se ha podido leer la memoria'}</h2><p className="mt-3 text-slate-600">{status === 'unconfigured' ? 'Conecta el archivo persistente del escáner para consultar aquí sus documentos.' : 'Revisa el acceso al archivo o recupera una copia verificada. Los documentos no se muestran hasta poder comprobar su integridad.'}</p><p className="mt-3 text-sm text-amber-900">Este estado no significa que no haya novedades.</p></section> : query.id && !item ? <section className={panel}><h2 className="text-xl font-semibold">Ficha o versión no encontrada</h2><Link className="mt-4 inline-block text-sky-700 underline" href={back}>Volver al archivo</Link></section> : item ? <>
      <Link className="mb-6 inline-flex items-center gap-2 text-sm font-medium text-sky-700" href={back}><ArrowLeft size={16} />Volver al archivo</Link>
      <div className="mb-6 flex flex-wrap gap-2"><span className={badge}>Revisión pendiente</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{KIND_LABELS[item.selected.kind]}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs">{CONTENT_LABELS[item.selected.contentKind]}</span>{query.version && <span className="rounded-full bg-sky-50 px-3 py-1 text-xs text-sky-800">Captura seleccionada del historial</span>}</div>
      <div className="grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
        <div className="min-w-0 space-y-6">
          {item.selected.kind === 'norma' && <section className={panel}><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-sky-700">01 · Entender</p><h2 className="text-xl font-semibold">En palabras sencillas</h2>
            {item.reading ? <><p className="mt-4 whitespace-pre-wrap leading-7">{item.reading.summary}</p><p className="mt-3 text-xs text-slate-500">Análisis registrado el {date(item.reading.record.observedAt)} sobre esta captura. Pendiente de revisión.</p><details className="mt-5 border-t border-slate-100 pt-4"><summary className="cursor-pointer font-medium">Impacto y acciones propuestas</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.reading.impact}</p><ul className="mt-4 space-y-4">{item.reading.actions.map((a, i) => <li key={i}><p className="text-sm font-medium">{a.accion}</p><blockquote className="mt-2 border-l-2 border-sky-200 pl-3 text-sm text-slate-600">«{a.cita}»<cite className="mt-1 block text-xs not-italic">{a.localizador}</cite></blockquote></li>)}</ul></details>
              <details className="mt-4 border-t border-slate-100 pt-4"><summary className="cursor-pointer font-medium">Ver las citas del análisis</summary><ul className="mt-4 space-y-4">{item.reading.evidence.map((e, i) => <li key={i}><span className="text-xs font-semibold uppercase text-sky-700">{e.campo}</span><blockquote className="mt-1 border-l-2 border-sky-200 pl-3 text-sm leading-6">«{e.cita}»<cite className="block text-xs not-italic text-slate-500">{e.localizador}</cite></blockquote></li>)}</ul></details></> : <p className="mt-4 leading-7 text-slate-600">{item.selected.contentKind === 'sumario' ? 'Solo conservamos el sumario. Hace falta el texto completo para explicar obligaciones y plazos.' : 'Esta captura todavía no tiene una explicación con citas vinculadas. Puedes consultar el texto conservado y su fuente.'}</p>}
          </section>}
          <section className={panel}><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-sky-700">02 · Comprobar</p><h2 className="text-xl font-semibold">Texto conservado</h2><p className="mt-2 text-xs text-slate-500">{CONTENT_LABELS[item.selected.contentKind]} · observado el {date(item.selected.observedAt)}</p><details className="mt-5" open={item.selected.contentKind === 'sumario'}><summary className="cursor-pointer text-sm font-medium text-sky-700">Leer la captura</summary><pre className="mt-4 max-h-[32rem] overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-4 font-sans text-sm leading-7">{item.selected.content}</pre></details>
            {item.previous && <details className="mt-5 border-t border-slate-100 pt-4"><summary className="cursor-pointer text-sm font-medium">Comparar con la captura anterior</summary><p className="mt-3 text-sm text-slate-600">{item.previous.contentHash === item.selected.contentHash ? 'El texto coincide; cambió la observación o sus metadatos.' : 'El contenido de las capturas es distinto. Esto puede deberse a una ampliación del texto recuperado; no acredita por sí solo una modificación legal.'}</p><Link className="mt-3 inline-block text-sm text-sky-700 underline" href={href(base, { ...query, version: item.previous.version })}>Abrir captura del {date(item.previous.observedAt)}</Link></details>}
          </section>
          <section className={panel}><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-sky-700">03 · Conectar</p><h2 className="text-xl font-semibold">Documentos relacionados</h2><p className="mt-2 text-sm text-slate-600">Enlaces registrados para consultar juntos. No acreditan causalidad ni corroboración independiente.</p>{item.related.length ? <ul className="mt-4 divide-y divide-slate-100">{item.related.map(r => <li key={r.id} className="py-3"><Link className="text-sm font-medium text-sky-800 hover:underline" href={href(base, { id: r.id })}>{r.title}</Link><p className="mt-1 text-xs text-slate-500">{KIND_LABELS[r.kind]} · {r.publisher}</p></li>)}</ul> : <p className="mt-4 text-sm text-slate-500">Aún no se han registrado relaciones para esta ficha.</p>}</section>
        </div>
        <aside className="min-w-0 space-y-5" aria-label="Fuente e historial">
          <section className={panel}><BookOpen size={20} className="mb-3 text-sky-700" /><h2 className="font-semibold">Fuente y fechas</h2><dl className="mt-4 space-y-4 text-sm"><div><dt className="text-slate-500">Publicador</dt><dd className="mt-1 break-words">{item.selected.publisher}</dd></div><div><dt className="text-slate-500">Fecha de publicación</dt><dd className="mt-1">{item.selected.publishedAt ? date(item.selected.publishedAt) : 'No consta'}</dd></div><div><dt className="text-slate-500">Última observación de esta ficha</dt><dd className="mt-1">{date(item.history[0].observedAt)}</dd></div><div><dt className="text-slate-500">Vigencia jurídica</dt><dd className="mt-1">Sin verificar</dd></div></dl>{sourceLink(item.selected.sourceUrl) ? <a className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-sky-700" href={sourceLink(item.selected.sourceUrl)!} target="_blank" rel="noopener noreferrer">Abrir fuente <ArrowUpRight size={16} /></a> : <p className="mt-5 text-xs text-slate-500">Registro interno; sin enlace público.</p>}</section>
          <section className={panel}><History size={20} className="mb-3 text-sky-700" /><h2 className="font-semibold">Historial de capturas</h2><p className="mt-2 text-xs text-slate-500">{item.history.length} observaciones conservadas. Fechas en Madrid.</p><ol className="mt-4 space-y-4">{item.history.map((r, i) => <li key={r.version} className="border-l-2 border-slate-200 pl-3"><Link aria-current={r.version === item.selected.version ? 'page' : undefined} className={`text-sm ${r.version === item.selected.version ? 'font-semibold text-sky-800' : 'text-slate-600 hover:underline'}`} href={href(base, { ...query, version: i === 0 ? undefined : r.version })}>{date(r.observedAt)}{i === 0 ? ' · última' : ''}</Link><p className="mt-1 text-xs text-slate-500">{CONTENT_LABELS[r.contentKind]}</p></li>)}</ol></section>
        </aside>
      </div>
    </> : <>
      <div className="mb-6 grid grid-cols-3 gap-3">{[[latest.filter(r => r.kind === 'norma').length, 'Normas'], [latest.filter(r => ['noticia', 'cambio_web'].includes(r.kind)).length, 'Fuentes de contexto'], [records.length, 'Capturas conservadas']].map(([count, label]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-2xl font-semibold">{count}</strong><p className="mt-1 text-xs leading-5 text-slate-500">{label}</p></div>)}</div>
      <form method="get" action={base} className="mb-6 flex flex-col gap-3 sm:flex-row"><div className="flex-1"><label htmlFor="memory-query" className="mb-1 block text-xs font-medium">Buscar en el archivo</label><input id="memory-query" name="q" defaultValue={query.q} placeholder="Vivienda, alquiler, una empresa…" className="w-full rounded-lg border border-slate-300 bg-white px-4 py-3 text-sm" /></div><div><label htmlFor="memory-kind" className="mb-1 block text-xs font-medium">Tipo de documento</label><select id="memory-kind" name="tipo" defaultValue={query.tipo || ''} className="w-full rounded-lg border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">Todos los documentos</option>{Object.entries(KIND_LABELS).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div><button className="inline-flex items-center justify-center gap-2 self-end rounded-lg bg-sky-700 px-5 py-3 text-sm font-semibold text-white hover:bg-sky-800"><Search size={16} />Buscar</button></form>
      <p className="mb-3 text-sm text-slate-500">{filtered.length} documentos · revisión pendiente</p>
      <div className="space-y-3">{filtered.slice(0, 100).map(r => <article key={r.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-2 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span className="font-semibold text-sky-700">{KIND_LABELS[r.kind]}</span><span>· {r.publisher}</span><span>· {CONTENT_LABELS[r.contentKind]}</span></div><h2 className="text-lg font-semibold"><Link className="hover:text-sky-700 hover:underline" href={href(base, { ...query, id: r.id, version: undefined })}>{r.title}</Link></h2><p className="mt-3 text-xs text-slate-500">Observado el {date(r.observedAt)} · <span className="text-amber-800">Sin revisión jurídica</span></p></article>)}</div>
      {filtered.length > 100 && <p className="mt-4 text-sm text-slate-600">Se muestran 100 documentos. Afina la búsqueda para encontrar el que necesitas.</p>}
      {!filtered.length && <section className={panel}><h2 className="font-semibold">{records.length ? 'No hay coincidencias con estos filtros' : 'El archivo todavía está vacío'}</h2><p className="mt-2 text-sm text-slate-600">{records.length ? 'Prueba otra búsqueda o consulta todos los documentos.' : 'Las capturas aparecerán cuando el escáner o un importador guarden documentos en esta memoria.'}</p><Link className="mt-4 inline-block text-sm text-sky-700 underline" href={base}>Ver todo el archivo</Link></section>}
      <p className="mt-6 text-xs leading-5 text-slate-500">El archivo muestra lo conservado, no toda la información publicada. Cero resultados no demuestra ausencia de novedades.</p>
    </>}
    <footer className="mt-10 border-t border-slate-200 pt-5 text-xs text-slate-500">RegTrack · Fuentes, memoria y decisiones con evidencia.</footer>
  </div>
}
