import {test,expect} from '@playwright/test'
test('administrator keeps verified access while anonymous callers are rejected',async({page})=>{
 expect((await page.request.get('/api/config')).status()).toBe(401)
 await page.goto('/login?next=/comunidad')
 await page.getByLabel('Email',{exact:true}).fill('administrator@example.test')
 await page.getByLabel('Contraseña',{exact:true}).fill('Community-test-123!')
 await page.getByRole('button',{name:'Entrar',exact:true}).click()
 await expect(page).toHaveURL(/\/comunidad$/)
 expect((await page.request.get('/api/config')).status()).toBe(200)
})
test('verified registration provisions a free subscriber and rejects administration',async({page})=>{
 const failures:string[]=[];page.on('pageerror',e=>failures.push(e.message))
 await page.goto('/registro')
 await expect(page.getByRole('heading',{name:'Crea tu cuenta de RegTrack'})).toBeVisible()
 expect((await page.request.post('/api/registro',{headers:{origin:'http://127.0.0.1:3100'},data:{nombre:'Ana'}})).status()).toBe(401)
 await page.goto('/login?next=/registro')
 await page.getByLabel('Email',{exact:true}).fill('subscriber@example.test')
 await page.getByLabel('Contraseña',{exact:true}).fill('Community-test-123!')
 await page.getByRole('button',{name:'Entrar',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Completa tu perfil'})).toBeVisible()
 await page.getByLabel('Nombre',{exact:true}).fill('Ana Propietaria')
 await page.getByLabel('Territorio principal').selectOption('Galicia')
 await page.getByRole('button',{name:'Guardar perfil'}).click()
 await expect(page).toHaveURL(/\/alertas$/)
 const account=await page.request.get('/api/cuenta')
 expect(account.status()).toBe(200);expect(await account.json()).toMatchObject({nombre:'Ana Propietaria',email:'subscriber@example.test',plan:'free'})
 expect((await page.request.get('/api/config')).status()).toBe(403)
 await page.goto('/registro');await expect(page).toHaveURL(/\/alertas$/)
 expect(failures).toEqual([])
 await page.screenshot({path:'test-results/registration-complete.png',fullPage:true})
})
