import type { CoverageSource, Jurisdiction } from "./coverage-model";

type Dossier = Pick<Jurisdiction, "mandate" | "sources">;
function source(id: string, title: string, url: string, publisher: string, family: string, role: CoverageSource["role"], scopeNote: string): CoverageSource {
  return { id, title, url, publisher, family, role, consultedAt: "2026-10-10", scopeNote };
}
/** Discovery register. Sources here do not count as reviewed commitments. */
export const territorialDossiers: Record<string, Dossier> = {
  "r-01": { mandate: null, sources: [source("andalucia-government", "Composición del Gobierno · XIII Legislatura", "https://www.juntadeandalucia.es/presidencia/portavoz/gobiernoaldia/217411/juanmamoreno/nuevogobiernoandaluz/consejeros/ejecutivo/xiiilegislatura/juntadeandalucia", "Junta de Andalucía", "gob-andalucia", "register", "Composición localizada que remite al BOJA extraordinario de 9 de julio de 2026. Hay que revisar el nuevo mandato y sus compromisos antes de atribuirle actuaciones anteriores.")] },
  "r-02": { mandate: null, sources: [source("aragon-transparency", "Transparencia Aragón", "https://www.aragon.es/transparencia", "Gobierno de Aragón", "gob-aragon", "register", "Portal de publicidad activa localizado. Falta identificar el acuerdo aplicable tras las elecciones de 2026 y separar las actuaciones de la legislatura anterior.")] },
  "r-03": { mandate: null, sources: [source("asturias-plans", "Planes y programas estratégicos", "https://transparencia.asturias.es/administracion/planes-estrategicos", "Principado de Asturias", "gob-asturias", "programme", "Catálogo sectorial consultado. No equivale a un inventario completo de compromisos de mandato.")] },
  "r-04": { mandate: null, sources: [source("balears-agreements", "Acuerdos de gobernabilidad", "https://www.caib.es/sites/transparencia/es/acuerdos_de_gobernabilidad/", "Govern de les Illes Balears", "gob-balears", "programme", "Página de acuerdos consultada; falta extraer el documento aplicable, su fecha y sus compromisos.")] },
  "r-05": { mandate: { label: "XI legislatura 2023–2027; objetivos 2024–2027", sourceId: "canarias-objectives" }, sources: [source("canarias-objectives", "BOC 3575/2023 · objetivos del Gobierno", "https://www.gobiernodecanarias.org/boc/2023/219/003.html", "Boletín Oficial de Canarias", "gob-canarias", "programme", "Resolución de 6 de noviembre de 2023. Describe la planificación y su periodo; no acredita ejecución. La página advierte que la versión oficial es el PDF firmado.")] },
  "r-08": { mandate: null, sources: [source("clm-accountability", "Compromiso 446 · informe anual de cumplimiento", "https://compromisos.castillalamancha.es/legislatura/3/area/4/subarea/22/compromiso/7455", "Junta de Castilla-La Mancha", "gob-clm", "government-report", "Ficha localizada en el índice público; la consulta directa agotó el tiempo de espera. Sus cifras de cumplimiento son declaraciones del Gobierno, pendientes de captura y contraste.")] },
  "r-09": { mandate: null, sources: [source("catalunya-programme", "Pla de Govern · XV Legislatura", "https://govern.cat/govern/docs/Pladegovern.pdf", "Generalitat de Catalunya", "gob-catalunya", "programme", "Documento localizado en el índice público con periodo 2024–2027. Pendientes captura, extracción y comprobación del mandato vigente.")] },
  "r-10": { mandate: null, sources: [source("valencia-plans", "Planes y programas · XI legislatura", "https://gvaoberta.gva.es/es/planes-y-programas-vigentes", "Generalitat Valenciana", "gob-valencia", "programme", "Catálogo localizado en el índice público. Consulta directa sin respuesta; no se ha comprobado la vigencia de todos sus documentos ni un inventario completo.")] },
  "r-12": { mandate: null, sources: [source("galicia-planning", "Planificación · Portal de Transparencia", "https://transparencia.xunta.gal/es/tema/transparencia-institucional/planificacion", "Xunta de Galicia", "gob-galicia", "programme", "Catálogo de planificación localizado. Los planes sectoriales pueden abarcar varias legislaturas; falta identificar el inventario del mandato y su seguimiento.")] },
  "r-13": { mandate: null, sources: [source("madrid-region-report", "Balance del Gobierno autonómico · diciembre de 2025", "https://www.comunidad.madrid/noticias/2025/12/17/diaz-ayuso-anuncia-casi-completo-cumplimiento-su-programa-gobierno-97-medidas-ya-activadas", "Comunidad de Madrid", "gob-madrid", "government-report", "Nota institucional localizada. Activar una medida no prueba haber completado su objetivo; el porcentaje anunciado no se adopta como valoración de RegTrack.")] },
  "r-15": { mandate: { label: "Acuerdo programático 2023–2027", sourceId: "navarra-accountability" }, sources: [source("navarra-accountability", "Seguimiento del Acuerdo Programático 2023–2027", "https://gobiernoabierto.navarra.es/es/gobernanza/rendicion-de-cuentas/gobierno-de-navarra", "Gobierno de Navarra", "gob-navarra", "government-report", "Portal consultado: enlaza el acuerdo y balances 2023–2024 y 2025. Los informes son del propio Gobierno; aún no se han importado ni contrastado sus compromisos.")] },
  "r-16": { mandate: null, sources: [source("euskadi-programme", "Programa de Gobierno 2024–2028 · XIII Legislatura", "https://bideoak2.euskadi.eus/paginas/page_98299/Programa_Gobierno_2024-2028_es.pdf", "Gobierno Vasco", "gob-euskadi", "programme", "Programa localizado en el índice público. Falta conservar y extraer los compromisos y comprobar su seguimiento; no constituye una revisión de resultados.")] },
  "r-17": { mandate: null, sources: [source("rioja-programme", "Programa de Gobierno", "https://web.larioja.org/portal-transparencia/55-gobierno/programa-de-gobierno", "Gobierno de La Rioja", "gob-rioja", "programme", "Página del programa localizada. Pendiente comprobar el documento vigente, extraer sus compromisos y contrastar las actuaciones vinculadas.")] },
  "m-28079": { mandate: null, sources: [source("madrid-local-programme", "Evaluación de la gestión municipal", "https://www.madrid.es/portales/munimadrid/es/Inicio/El-Ayuntamiento/Calidad-y-Evaluacion/Estrategia-y-planificacion/Portal-de-Evaluacion-de-la-Gestion-Municipal-mejora-transparencia-y-rendicion-de-cuentas/?vgnextchannel=486a261f46839710VgnVCM1000001d4a900aRCRD&vgnextfmt=default&vgnextoid=fa49100298580a10VgnVCM200000f921e388RCRD", "Ayuntamiento de Madrid", "ayto-madrid", "government-report", "Portal localizado que anuncia seguimiento del programa 2023–2027. Pendiente extraer sus actuaciones y contrastar ejecución. Es distinto del balance de la Comunidad de Madrid.")] },
  "m-08019": { mandate: null, sources: [source("barcelona-accounts", "Informes de la Sindicatura de Cuentas", "https://seuelectronica.ajuntament.barcelona.cat/ca/informes-sindicatura-de-cuentas", "Ayuntamiento de Barcelona · documentos de la Sindicatura", "sindicatura-catalunya", "control", "Índice de informes localizado. Debe leerse el informe específico, su ejercicio y alcance antes de usarlo como corroboración de una promesa.")] },
  "m-46250": { mandate: null, sources: [source("valencia-local-accounts", "Cuentas anuales e informes", "https://www.valencia.es/web/gobierno-abierto/cas/las-cuentas-claras/presupuesto/cuentas-anuales-e-informes", "Ajuntament de València", "ayto-valencia", "government-report", "Repositorio de cuentas localizado. Publicar una cuenta no demuestra que esté auditada ni que sus gastos hayan conseguido el resultado prometido.")] },
};
